"""baseline schema

Revision ID: 1ccc65108abc
Revises:
Create Date: 2026-06-11 21:01:19.478165

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ccc65108abc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for the gin_trgm_ops indexes on notifications below.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_metric_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_metric_logs_created_at", "api_metric_logs", ["created_at"], unique=False
    )
    op.create_index("ix_api_metric_logs_path", "api_metric_logs", ["path"], unique=False)
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "monitoring_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_monitoring_tokens_token_hash", "monitoring_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "plugin_configs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("allow_user_configs", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Enum("viewer", "admin", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_sub"), "users", ["sub"], unique=True)
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_override", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_access_tokens_token_hash", "access_tokens", ["token_hash"], unique=True)
    op.create_index(
        "ix_access_tokens_user_global", "access_tokens", ["user_id", "is_global"], unique=False
    )
    op.create_index(op.f("ix_access_tokens_user_id"), "access_tokens", ["user_id"], unique=False)
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("match_type", sa.String(length=32), nullable=False),
        sa.Column("match_pattern", sa.Text(), nullable=False),
        sa.Column("match_target", sa.String(length=32), nullable=False),
        sa.Column("notification_scope", sa.String(length=32), nullable=False),
        sa.Column("send_email", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_user_id"), "alert_rules", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_username", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_actor_user_id", "audit_logs", ["actor_user_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("severities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routing_rules_user_id"), "routing_rules", ["user_id"], unique=False)
    op.create_table(
        "user_plugin_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_plugin_configs_user_id"), "user_plugin_configs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_plugin_configs_user_plugin",
        "user_plugin_configs",
        ["user_id", "plugin_id"],
        unique=True,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=True),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["token_id"], ["access_tokens.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_fingerprint"), "notifications", ["fingerprint"], unique=False
    )
    op.create_index(
        "ix_notifications_message_gin",
        "notifications",
        ["message"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"message": "gin_trgm_ops"},
    )
    op.create_index("ix_notifications_received_at", "notifications", ["received_at"], unique=False)
    op.create_index(
        "ix_notifications_sender_name_gin",
        "notifications",
        ["sender_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sender_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_notifications_title_gin",
        "notifications",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_notifications_token_last_received",
        "notifications",
        ["token_id", "last_received_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_token_received",
        "notifications",
        ["token_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "user_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("email_sent", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_alerts_created_at", "user_alerts", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_user_alerts_notification_id"), "user_alerts", ["notification_id"], unique=False
    )
    op.create_index(op.f("ix_user_alerts_user_id"), "user_alerts", ["user_id"], unique=False)
    op.create_index(
        "ix_user_alerts_user_id_is_read", "user_alerts", ["user_id", "is_read"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_alerts_user_id_is_read", table_name="user_alerts")
    op.drop_index(op.f("ix_user_alerts_user_id"), table_name="user_alerts")
    op.drop_index(op.f("ix_user_alerts_notification_id"), table_name="user_alerts")
    op.drop_index("ix_user_alerts_created_at", table_name="user_alerts")
    op.drop_table("user_alerts")
    op.drop_index("ix_notifications_token_received", table_name="notifications")
    op.drop_index("ix_notifications_token_last_received", table_name="notifications")
    op.drop_index(
        "ix_notifications_title_gin",
        table_name="notifications",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_notifications_sender_name_gin",
        table_name="notifications",
        postgresql_using="gin",
        postgresql_ops={"sender_name": "gin_trgm_ops"},
    )
    op.drop_index("ix_notifications_received_at", table_name="notifications")
    op.drop_index(
        "ix_notifications_message_gin",
        table_name="notifications",
        postgresql_using="gin",
        postgresql_ops={"message": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_notifications_fingerprint"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_user_plugin_configs_user_plugin", table_name="user_plugin_configs")
    op.drop_index(op.f("ix_user_plugin_configs_user_id"), table_name="user_plugin_configs")
    op.drop_table("user_plugin_configs")
    op.drop_index(op.f("ix_routing_rules_user_id"), table_name="routing_rules")
    op.drop_table("routing_rules")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_alert_rules_user_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_access_tokens_user_id"), table_name="access_tokens")
    op.drop_index("ix_access_tokens_user_global", table_name="access_tokens")
    op.drop_index("ix_access_tokens_token_hash", table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_index(op.f("ix_users_sub"), table_name="users")
    op.drop_table("users")
    op.drop_table("plugin_configs")
    op.drop_index("ix_monitoring_tokens_token_hash", table_name="monitoring_tokens")
    op.drop_table("monitoring_tokens")
    op.drop_table("app_settings")
    op.drop_index("ix_api_metric_logs_path", table_name="api_metric_logs")
    op.drop_index("ix_api_metric_logs_created_at", table_name="api_metric_logs")
    op.drop_table("api_metric_logs")
    # ### end Alembic commands ###
